name: ShellCheck

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'
        format: gcc
        severity: warning
        
    - name: Test script syntax
      run: |
        for script in scripts/*.sh; do
          echo "Testing syntax of $script"
          bash -n "$script"
        done